/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iremalimelis;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

public class ActivityCenterFrame extends javax.swing.JFrame {

    /**
     * Creates new form ActivityCenterFrame
     */
    
    SearchRemoveFrame seReF = new SearchRemoveFrame(this);
    
    public void fillComboBox() {
        seReF.getCustIdCMB().setModel(new DefaultComboBoxModel(ActivityCenterSys.getCustomerId()));
    }
    
    public void fillCMB_courseName(){
        
    }
    
    public ActivityCenterFrame() {
        initComponents();
    }
    
    public void clear(){
        TF_id.setText("");
        TF_name.setText("");
        SLIDER_age.setValue(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNG_gender = new javax.swing.ButtonGroup();
        BTNG_branchName = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TF_id = new javax.swing.JTextField();
        TF_name = new javax.swing.JTextField();
        SLIDER_age = new javax.swing.JSlider();
        RBTN_female = new javax.swing.JRadioButton();
        RBTN_male = new javax.swing.JRadioButton();
        RBTN_art = new javax.swing.JRadioButton();
        RBTN_sport = new javax.swing.JRadioButton();
        CMB_courseName = new javax.swing.JComboBox<>();
        CMB_courseDate = new javax.swing.JComboBox<>();
        CMB_instructorName = new javax.swing.JComboBox<>();
        BTN_add = new javax.swing.JButton();
        BTN_display = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_display = new javax.swing.JTextArea();
        BTN_removeSearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LB_age = new javax.swing.JLabel();
        BTN_totCust = new javax.swing.JButton();
        LB_totCust = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Activity Centers");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(550, 200));
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Branch Name: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel2.setText("Course Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel3.setText("Customer Id:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 28, -1, -1));

        jLabel4.setText("Customer Name: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 66, -1, -1));

        jLabel5.setText("Age: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel6.setText("Gender: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel7.setText("Course Date: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel8.setText("Instructor Name: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        getContentPane().add(TF_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, -1));
        getContentPane().add(TF_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 130, -1));

        SLIDER_age.setMaximum(65);
        SLIDER_age.setMinimum(16);
        SLIDER_age.setValue(16);
        SLIDER_age.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SLIDER_ageMouseMoved(evt);
            }
        });
        getContentPane().add(SLIDER_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        BTNG_gender.add(RBTN_female);
        RBTN_female.setSelected(true);
        RBTN_female.setText("Female");
        RBTN_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTN_femaleActionPerformed(evt);
            }
        });
        getContentPane().add(RBTN_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        BTNG_gender.add(RBTN_male);
        RBTN_male.setText("Male");
        getContentPane().add(RBTN_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        BTNG_branchName.add(RBTN_art);
        RBTN_art.setSelected(true);
        RBTN_art.setText("Art");
        RBTN_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTN_artActionPerformed(evt);
            }
        });
        getContentPane().add(RBTN_art, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        BTNG_branchName.add(RBTN_sport);
        RBTN_sport.setText("Sport");
        RBTN_sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTN_sportActionPerformed(evt);
            }
        });
        getContentPane().add(RBTN_sport, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        CMB_courseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Music", "Painting" }));
        CMB_courseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMB_courseNameActionPerformed(evt);
            }
        });
        getContentPane().add(CMB_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 160, -1));

        CMB_courseDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        getContentPane().add(CMB_courseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 160, -1));

        CMB_instructorName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hatice Zehra Yılmaz", "Serkan Genç", "Fusün Yürüten" }));
        CMB_instructorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMB_instructorNameActionPerformed(evt);
            }
        });
        getContentPane().add(CMB_instructorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 160, -1));

        BTN_add.setText("ADD");
        BTN_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_addActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 90, 40));

        BTN_display.setText("DISPLAY");
        BTN_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_displayActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 90, 40));

        TA_display.setColumns(20);
        TA_display.setRows(5);
        jScrollPane1.setViewportView(TA_display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 340, 320));

        BTN_removeSearch.setText("Remove / Search");
        BTN_removeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_removeSearchActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_removeSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 130, 50));

        jLabel9.setText("65");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 20, 20));

        jLabel10.setText("16");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 20, -1));
        getContentPane().add(LB_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 50, 30));

        BTN_totCust.setText("Total Customer =");
        BTN_totCust.setAlignmentX(100.0F);
        BTN_totCust.setAlignmentY(100.0F);
        BTN_totCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_totCustActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_totCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 150, 50));
        getContentPane().add(LB_totCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMB_courseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMB_courseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMB_courseNameActionPerformed

    private void BTN_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_addActionPerformed
        
        if(TF_id.getText().isEmpty() || TF_name.getText().isEmpty()){
            TA_display.setText("Please Fill all fields!!");
        }
        else{
            int ID = Integer.parseInt(TF_id.getText());
            String NAME = TF_name.getText();
            int AGE = SLIDER_age.getValue();
                   
            String GENDER;
            if(RBTN_male.isSelected()){
                GENDER = "Male";
            }
            else{
                GENDER = "Female";
            }
            
            String branch;
            if(RBTN_art.isSelected()){
                branch = "Art";
            }
            else{
                branch = "Sport";
            }
            
            String courseNm = (String)CMB_courseName.getSelectedItem();
            String date = (String)CMB_courseDate.getSelectedItem();
            String instName = (String)CMB_instructorName.getSelectedItem();
            
            Customer cust = new Customer(ID, NAME, AGE, GENDER);
            
            boolean res = ActivityCenterSys.addCustomer(branch, instName, courseNm, date, 0, cust);
            
            if(res)
                TA_display.setText("Customer record is added!!");
            else
                TA_display.setText("Customer ID should be different!!!");
            
            clear();
        }
    }//GEN-LAST:event_BTN_addActionPerformed

    private void BTN_removeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_removeSearchActionPerformed
        // TODO add your handling code here:
        if(!ActivityCenterSys.list.isEmpty()){
            fillComboBox();
            this.setVisible(false);
            seReF.setVisible(true);
            LB_totCust.setText("");
            TA_display.setText("");
        }
        else{
            TA_display.setText("Enter activity to remove or search!!");
        }
    }//GEN-LAST:event_BTN_removeSearchActionPerformed

    private void BTN_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_displayActionPerformed
        // TODO add your handling code here:
        if(!ActivityCenterSys.list.isEmpty()){
            TA_display.setText(ActivityCenterSys.display());
        }
        else{
            TA_display.setText("Enter activity to display!!");
        }
    }//GEN-LAST:event_BTN_displayActionPerformed

    private void RBTN_sportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTN_sportActionPerformed
        // TODO add your handling code here:
        if(RBTN_sport.isSelected()){
            CMB_courseName.removeAllItems();
            CMB_courseName.addItem("Basketball");
            CMB_courseName.addItem("Gymnastics");
            
            CMB_instructorName.removeAllItems();
            CMB_instructorName.addItem("Erkan Uçar");
            CMB_instructorName.addItem("Burcu Liman");
            CMB_instructorName.addItem("Serpil Tın");
        }
    }//GEN-LAST:event_RBTN_sportActionPerformed

    private void RBTN_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTN_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBTN_femaleActionPerformed

    private void RBTN_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTN_artActionPerformed
        // TODO add your handling code here:
        if(RBTN_art.isSelected()){
            CMB_courseName.removeAllItems();
            CMB_courseName.addItem("Music");
            CMB_courseName.addItem("Painting");
            
            CMB_instructorName.removeAllItems();
            CMB_instructorName.addItem("Hatice Zehra Yılmaz");
            CMB_instructorName.addItem("Serkan Genç");
            CMB_instructorName.addItem("Füsun Yürüten");
        }
    }//GEN-LAST:event_RBTN_artActionPerformed

    private void CMB_instructorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMB_instructorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMB_instructorNameActionPerformed

    private void SLIDER_ageMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SLIDER_ageMouseMoved
        // TODO add your handling code here:
        LB_age.setText("" + SLIDER_age.getValue());
    }//GEN-LAST:event_SLIDER_ageMouseMoved

    private void BTN_totCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_totCustActionPerformed
        // TODO add your handling code here:
        LB_totCust.setText("" + ActivityCenter.getNumOfCustomer());
    }//GEN-LAST:event_BTN_totCustActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTNG_branchName;
    private javax.swing.ButtonGroup BTNG_gender;
    private javax.swing.JButton BTN_add;
    private javax.swing.JButton BTN_display;
    private javax.swing.JButton BTN_removeSearch;
    private javax.swing.JButton BTN_totCust;
    private javax.swing.JComboBox<String> CMB_courseDate;
    private javax.swing.JComboBox<String> CMB_courseName;
    private javax.swing.JComboBox<String> CMB_instructorName;
    private javax.swing.JLabel LB_age;
    private javax.swing.JLabel LB_totCust;
    private javax.swing.JRadioButton RBTN_art;
    private javax.swing.JRadioButton RBTN_female;
    private javax.swing.JRadioButton RBTN_male;
    private javax.swing.JRadioButton RBTN_sport;
    private javax.swing.JSlider SLIDER_age;
    private javax.swing.JTextArea TA_display;
    private javax.swing.JTextField TF_id;
    private javax.swing.JTextField TF_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
